name: game_management
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.2
  flutterfire_ui: ^0.4.3+20
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  firebase_crashlytics: ^3.3.0
  firebase_messaging: ^14.6.0
  intl: ^0.18.0
  flutter_gen: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  retrofit_generator: ^6.0.0+1
  flutter_gen_runner: ^5.3.1

flutter:
  generate: true

flutter_intl:
  enabled: true
  main_locale: pl  

  uses-material-design: true

  assets:
    - assets/
