// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjoObyz9rbCAUa7KoIuzdfEYkWOn0i4RA',
    appId: '1:625818006534:web:e500a5412f25f8524cff87',
    messagingSenderId: '625818006534',
    projectId: 'gamemanagement1120',
    authDomain: 'gamemanagement1120.firebaseapp.com',
    storageBucket: 'gamemanagement1120.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy_aT-pmgDkV5PPxkgWQLTVftVM9Swm34',
    appId: '1:625818006534:android:8463430415f9645b4cff87',
    messagingSenderId: '625818006534',
    projectId: 'gamemanagement1120',
    storageBucket: 'gamemanagement1120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2usP7QzmG-b5M3pFa_qzqxwZG7AIFTmU',
    appId: '1:625818006534:ios:be110a6a8b1368494cff87',
    messagingSenderId: '625818006534',
    projectId: 'gamemanagement1120',
    storageBucket: 'gamemanagement1120.appspot.com',
    iosClientId: '625818006534-b4h3de579caa0af0o60hr1b3scabiiaj.apps.googleusercontent.com',
    iosBundleId: 'com.eryklorenc.gameManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2usP7QzmG-b5M3pFa_qzqxwZG7AIFTmU',
    appId: '1:625818006534:ios:be110a6a8b1368494cff87',
    messagingSenderId: '625818006534',
    projectId: 'gamemanagement1120',
    storageBucket: 'gamemanagement1120.appspot.com',
    iosClientId: '625818006534-b4h3de579caa0af0o60hr1b3scabiiaj.apps.googleusercontent.com',
    iosBundleId: 'com.eryklorenc.gameManagement',
  );
}
